spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: entities-service
          uri: lb://entities-service
          predicates:
            - Path=/entities/**